# Generated by Django 5.2.6 on 2025-12-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedblock',
            old_name='tartget_user',
            new_name='target_user',
        ),
    ]
