# Generated by Django 5.2.6 on 2025-12-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_page_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='storage/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='storage/'),
        ),
    ]
