# Generated by Django 5.2.6 on 2025-12-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_page_avatar_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
